spring.application.name=lifevault

# Database Configuration (PostgreSQL)
# Local DB: psql -h localhost -p 5433 -U postgres -d lifevault
spring.datasource.url=jdbc:postgresql://localhost:5433/lifevault
spring.datasource.username=postgres
spring.datasource.password=root@1998
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JPA / Hibernate
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
# spring.jpa.properties.hibernate.format_sql=true

# JWT Configuration
lifevault.app.jwtSecret=LifeVaultSecretKeyForJwtTokenGenerationShouldBeLongAndSecure
lifevault.app.jwtExpirationMs=86400000
